# typed: false
# frozen_string_literal: true

# This file was generated by `brew tap cjan/ash/ash`. Do not edit it manually.
# Instead, please edit the formula template and run `make release-homebrew`.

class Ash < Formula
  desc "AI-powered shell assistant that translates natural language to zsh commands"
  homepage "https://github.com/golark/ash"
  version "1.0.6-3-g1078764-dirty"
  url "https://github.com/golark/ash/releases/download/v#{version}/ash-v#{version}-darwin-arm64.tar.gz"
  sha256 "36f960f6b2fb5e004f09b600b88c28f5a23fa5a30b0b82cc745695f190235518"
  license "Apache-2.0"
  head "https://github.com/golark/ash.git", branch: "main"

  # No build dependencies needed for prebuilt binary

  def install
    # Install binary from prebuilt tarball
    bin.install "ash"
    # Install widget script
    prefix.install "widget.zsh"
  end

  def post_install
    # Create directory for model storage
    model_dir = var/"ash"
    model_dir.mkpath

    # Download the model if it doesn't exist
    model_path = model_dir/"model.gguf"
    unless model_path.exist?
      model_url = "https://github.com/golark/ash/releases/download/v#{version}/ash-model.gguf"
      ohai "Downloading ASH model..."
      system "curl", "-L", "-o", model_path, model_url
    end
  end

  def caveats
    <<~EOS
      The ASH model has been downloaded to:
        #{var}/ash/model.gguf

      To remove the model when uninstalling, run:
        rm -rf #{var}/ash
    EOS
  end

  test do
    # Test that ash can be invoked (it will show usage on empty input)
    output = shell_output("#{bin}/ash 2>&1", 1)
    assert_match(/Usage:/, output)
  end
end

