# typed: false
# frozen_string_literal: true

# This file was generated by `brew tap cjan/ash/ash`. Do not edit it manually.
# Instead, please edit the formula template and run `make release-homebrew`.

class Ash < Formula
  desc "AI-powered shell assistant that translates natural language to zsh commands"
  homepage "https://github.com/golark/ash"
  version "1.0.11"
  url "https://github.com/golark/ash/releases/download/v#{version}/ash-v#{version}-darwin-arm64.tar.gz"
  sha256 "ce394c9c43bae887537307804f1bef7e9520fea817deecf84032031367096bad"
  license "Apache-2.0"
  head "https://github.com/golark/ash.git", branch: "main"

  # No build dependencies needed for prebuilt binary

  def install
    # Install binary from prebuilt tarball
    bin.install "ash"
    # Install widget script
    prefix.install "widget.zsh"
  end

  def post_install
    # Create directory for model storage
    model_dir = var/"ash"
    model_dir.mkpath

    # Download the model if it doesn't exist
    model_path = model_dir/"model.gguf"
    unless model_path.exist?
      model_url = "https://github.com/golark/ash/releases/download/v#{version}/ash-model.gguf"
      ohai "Downloading ASH model..."
      system "curl", "-L", "-o", model_path, model_url
    end
  end

  def caveats
    <<~EOS
    # On first use, ASH will download a machine learning model locally to ensure all generations run fully on your device (no external API calls).
    # This download may take a little time. Please be patient during the initial setup.
    #
    # To enable the shell assistant widget automatically, add the following line to your .zshrc:
    #   source #{opt_prefix}/widget.zsh
    # Then reload your terminal.
    EOS
  end

  test do
    # Test that ash can be invoked (it will show usage on empty input)
    output = shell_output("#{bin}/ash 2>&1", 1)
    assert_match(/Usage:/, output)
  end
end

