# typed: false
# frozen_string_literal: true

# This file was generated by `brew tap cjan/ash/ash`. Do not edit it manually.
# Instead, please edit the formula template and run `make release-homebrew`.

class Ash < Formula
  desc "AI-powered shell assistant that translates natural language to zsh commands"
  homepage "https://github.com/golark/ash"
  version "1.0.5-dirty"
  url "https://github.com/golark/ash/releases/download/v#{version}/ash-v#{version}-darwin-arm64.tar.gz"
  sha256 "ca2efb9522a0f70559d005454b1330ea35bd58df4d0b01ddff6f1c0d8b67e107"
  license "Apache-2.0"
  head "https://github.com/golark/ash.git", branch: "main"

  # No build dependencies needed for prebuilt binary

  def install
    # Install binary from prebuilt tarball
    bin.install "ash"
    # Install widget script
    prefix.install "widget.zsh"
  end

  test do
    # Test that ash can be invoked (it will show usage on empty input)
    output = shell_output("#{bin}/ash 2>&1", 1)
    assert_match(/Usage:/, output)
  end
end

